# Your build pipeline references a secret variable named ‘swa_deployment_token’. Create or edit the build pipeline for this YAML file, 
# define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

parameters:
  artifactName: ''
  displayName: ''
  deploymentToken: ''

steps:
- download: current
  artifact: ${{parameters.artifactName}}
- task: AzureStaticWebApp@0
  displayName: ${{parameters.displayName}}
  inputs:
    app_location: '' #Set this an empty string ('') when bypassing automatic build and only deploy is required.
    skip_app_build: true
    skip_api_build: true
    cwd: '$(Pipeline.Workspace)/${{parameters.artifactName}}'   
    azure_static_web_apps_api_token: ${{parameters.deploymentToken}}
    verbose: True