# Your build pipeline references a secret variable named ‘swa_deployment_token’. Create or edit the build pipeline for this YAML file, 
# define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

parameters:
  artifactName: ''
  displayName: ''
  deploymentToken: ''
  environement: ''

steps:
- download: current
  artifact: ${{parameters.artifactName}}

  # TODO: Use the file copy task to copy the appopraite AppSettings.${{environment}}.json
  # into the wwwroot folder (replace the existing AppSettings.json)
- task: AzureStaticWebApp@0
  displayName: ${{parameters.displayName}}
  inputs:
    app_location: '/wwwroot'  # Specify location the current build files (Blazor is wwwroot)
    output_location: '' # Leave this empty - we are not building in this task
    skip_app_build: true
    skip_api_build: true
    cwd: '$(Pipeline.Workspace)/${{parameters.artifactName}}-${{environment}}'   
    azure_static_web_apps_api_token: ${{parameters.deploymentToken}}
    verbose: True