# Your build pipeline references a secret variable named ‘swa_deployment_token’. Create or edit the build pipeline for this YAML file, 
# define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

parameters:
  artifactName: ''
  displayName: ''
  deploymentToken: ''

steps:

- task: DownloadPipelineArtifact@2
  displayName: 'Download Blazor WASM Artifact'
  inputs:
    artifact: ${{parameters.artifactName}}
    path: '$(Pipeline.Workspace)/${{parameters.artifactName}}'

- task: AzureStaticWebApp@0
  displayName: ${{parameters.displayName}}
  inputs:
    app_location: '/' # Root of artifact
    skip_app_build: true
    skip_api_build: true
    output_location: '$(Pipeline.Workspace)/${{parameters.artifactName}}'
    azure_static_web_apps_api_token: ${{parameters.deploymentToken}}